apiVersion: v1
kind: ConfigMap
metadata:
  name: singlepod-configmap
  namespace: singlepod
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Simple Page</title>
    </head>
    <body>
      <h1>Hello World!</h1>
      <p>This is a simple HTML paragraph.</p>
    </body>
    </html>
