apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: singlepod
  name: singlepod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: singlepod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: singlepod
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: singlepod-vol
          mountPath: /usr/share/nginx/html/
      volumes:
        - name: singlepod-vol
          configMap:
            name: singlepod-configmap
